#!/bin/bash
# winltfs build driver. Run inside an MSYS2 MINGW64 shell after setup.sh:
#   ./build.sh       # build everything and stage dist/
#   ./build.sh make  # just compile the LTFS tree
#   ./build.sh dist  # just (re)stage dist/
#   ./build.sh clean
set -uo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRC="$ROOT/ltfs"
DIST="${DIST:-$ROOT/dist}"   # override with DIST=... to stage elsewhere

do_make() {
    cd "$SRC"
    make -j"$(nproc)"
}

do_dist() {
    mkdir -p "$DIST"
    echo "==> Staging executables and plugins"
    cp "$SRC/src/.libs/ltfs.exe" \
       "$SRC/src/utils/.libs/mkltfs.exe" \
       "$SRC/src/utils/.libs/ltfsck.exe" \
       "$SRC/src/utils/.libs/unltfs.exe" \
       "$SRC/src/libltfs/.libs/libltfs.dll" \
       "$SRC/src/tape_drivers/windows/ltotape/.libs/libdriver-ltotape-win.dll" \
       "$SRC/src/tape_drivers/generic/file/.libs/libdriver-file.dll" \
       "$SRC/src/iosched/.libs/libiosched-unified.dll" \
       "$SRC/src/iosched/.libs/libiosched-fcfs.dll" \
       "$SRC/src/kmi/.libs/libkmi-flatfile.dll" \
       "$SRC/src/kmi/.libs/libkmi-simple.dll" \
       "$DIST/"
    cp "$SRC"/messages/lib*.dll "$DIST/"          # ICU message catalogs
    cp "$ROOT/build/wfsp/bin/winfsp-x64.dll" "$DIST/"

    echo "==> Copying MinGW runtime DLLs"
    cd "$DIST"
    for _ in 1 2 3; do  # iterate: copied DLLs may pull more deps
        ldd ./*.exe ./*.dll 2>/dev/null \
            | awk '/mingw64/ {print $3}' | sort -u \
            | while read -r dep; do cp -n "$dep" . 2>/dev/null || true; done
    done

    echo "==> Generating ltfs.conf"
    cat > "$DIST/ltfs.conf" <<EOF
# Generated by build.sh - plugin registry for this dist directory
plugin driver ltotape libdriver-ltotape-win.dll
plugin driver file libdriver-file.dll
plugin iosched unified libiosched-unified.dll
plugin iosched fcfs libiosched-fcfs.dll
plugin kmi flatfile libkmi-flatfile.dll
plugin kmi simple libkmi-simple.dll
default driver ltotape
default iosched unified
default kmi none
EOF

    echo "==> Staging drive icons"
    mkdir -p "$DIST/drive-icons"
    cp "$ROOT"/resources/drive-icons/*.ico "$DIST/drive-icons/"

    echo "==> Staging license texts"
    cp "$ROOT/LICENSE" "$DIST/"          # LTFS engine: LGPL v2.1
    cp -r "$ROOT/licenses" "$DIST/"      # third-party runtime component licenses

    echo "==> dist ready: $DIST  ($(ls -1 "$DIST" | wc -l) files)"
}

cmd=${1:-all}
case "$cmd" in
make)      do_make ;;
dist)      do_dist ;;
all)       do_make && do_dist ;;
clean)     cd "$SRC" && make clean ;;
*)         echo "usage: build.sh [all|make|dist|clean]" >&2; exit 2 ;;
esac
