#!/bin/bash
# winltfs build driver. Run inside an MSYS2 MINGW64 shell after setup.sh:
#   ./build.sh           # build everything and stage dist/
#   ./build.sh make      # just compile the LTFS tree
#   ./build.sh filedebug # just the file-emulator backend
#   ./build.sh dist      # just (re)stage dist/
#   ./build.sh clean
set -uo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRC="$ROOT/ltfs"
DIST="${DIST:-$ROOT/dist}"   # override with DIST=... to stage elsewhere

do_make() {
    cd "$SRC"
    make -j"$(nproc)"
}

do_filedebug() {
    # The file-emulator tape backend (test the filesystem with no tape
    # hardware). Not part of HP's Windows SUBDIRS, so it is built directly.
    cd "$SRC/messages"
    ./make_message_src.sh driver_generic_file_dat.o
    cd "$SRC/src/tape_drivers/generic/file"
    x86_64-w64-mingw32-gcc -shared -o libdriver-file.dll filedebug_tc.c \
        -DHAVE_CONFIG_H -I"$SRC" -I"$SRC/src" \
        -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 \
        -DWINVER=0x0601 -D_WIN32_WINNT=0x0601 \
        -I"$ROOT/build/wfsp/inc/fuse" $(pkg-config --cflags libxml-2.0 icu-uc) \
        -L"$SRC/src/libltfs/.libs" -lltfs \
        -L"$SRC/messages" -ldriver_generic_file \
        -L"$ROOT/build/wfsp/lib" -lwinfsp-x64 -lws2_32 \
        -Wl,--out-implib,libdriver-file.dll.a
    echo "filedebug backend built"
}

do_dist() {
    mkdir -p "$DIST"
    echo "==> Staging executables and plugins"
    cp "$SRC/src/.libs/ltfs.exe" \
       "$SRC/src/utils/.libs/mkltfs.exe" \
       "$SRC/src/utils/.libs/ltfsck.exe" \
       "$SRC/src/utils/.libs/unltfs.exe" \
       "$SRC/src/libltfs/.libs/libltfs.dll" \
       "$SRC/src/tape_drivers/windows/ltotape/.libs/libdriver-ltotape-win.dll" \
       "$SRC/src/iosched/.libs/libiosched-unified.dll" \
       "$SRC/src/iosched/.libs/libiosched-fcfs.dll" \
       "$SRC/src/kmi/.libs/libkmi-flatfile.dll" \
       "$SRC/src/kmi/.libs/libkmi-simple.dll" \
       "$DIST/"
    cp "$SRC/src/tape_drivers/generic/file/libdriver-file.dll" "$DIST/" 2>/dev/null \
        || echo "    (filedebug backend not built - emulator unavailable)"
    cp "$SRC"/messages/lib*.dll "$DIST/"          # ICU message catalogs
    cp "$ROOT/build/wfsp/bin/winfsp-x64.dll" "$DIST/"

    echo "==> Copying MinGW runtime DLLs"
    cd "$DIST"
    for _ in 1 2 3; do  # iterate: copied DLLs may pull more deps
        ldd ./*.exe ./*.dll 2>/dev/null \
            | awk '/mingw64/ {print $3}' | sort -u \
            | while read -r dep; do cp -n "$dep" . 2>/dev/null || true; done
    done

    echo "==> Generating ltfs.conf"
    cat > "$DIST/ltfs.conf" <<EOF
# Generated by build.sh - plugin registry for this dist directory
plugin driver ltotape libdriver-ltotape-win.dll
plugin driver file libdriver-file.dll
plugin iosched unified libiosched-unified.dll
plugin iosched fcfs libiosched-fcfs.dll
plugin kmi flatfile libkmi-flatfile.dll
plugin kmi simple libkmi-simple.dll
default driver ltotape
default iosched unified
default kmi none
EOF

    echo "==> Staging drive icons"
    mkdir -p "$DIST/drive-icons"
    cp "$ROOT"/resources/drive-icons/*.ico "$DIST/drive-icons/"

    echo "==> Staging license texts"
    cp "$ROOT/LICENSE" "$DIST/"          # LTFS engine: LGPL v2.1
    cp -r "$ROOT/licenses" "$DIST/"      # third-party runtime component licenses

    echo "==> dist ready: $DIST  ($(ls -1 "$DIST" | wc -l) files)"
}

cmd=${1:-all}
case "$cmd" in
make)      do_make ;;
filedebug) do_filedebug ;;
dist)      do_dist ;;
all)       do_make && do_filedebug && do_dist ;;
clean)     cd "$SRC" && make clean ;;
*)         echo "usage: build.sh [all|make|filedebug|dist|clean]" >&2; exit 2 ;;
esac
